name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://doc-10-10-docs.googleusercontent.com/docs/securesc/gdk8gt42plpm2mhvupcepifu6umalbfj/p013l6136fnv20pko77g8v3a7kadbdvl/1654574700000/06555270420133642056/06555270420133642056/1Iyou0gb5kVmv9FixoI5nQhld6m1qLIxu?e=download&ax=ACxEAsb0KOf9igwffib4OItOZFJaBJp14hw5E-UGdTjmtFzMWkXMkZLqj0-sx1Wu9GqHIE_h-gtNdIFLwhuYjvpAHTnL2v0ZbSdMSlHewr58LfS-DKXK1gmZiF1G5Rg3FEH5UoqO1CFwu5yQN__VcpzYXn6ZXKp2qe9yhq_ZvRKLMPCSbP9m6r8kzLxERpg_XCCeaPmM_qe6Cx50XwSkXC7JJ7VVoTc7mSqkN7_hcDJ7_qwUyoywPJrZxWppvxZPdA3JvUYX-IxL9bPEmN8eVY5pLMT84f3Ey-1RXu8gDbr-hUWB6XpHlwBdygUqe_XxqrpalLDUmaqyxw_qzNpVi5Vab52EFejcZGY7_N5LohERTbpDo7xOnis2nzTP2yPyLRkdY97vc86TcqDpuRAcbzR5CDJjakPJaEfvlqto-im3mmAjWRSPsZrXMZaP3pTytkmCQ3gn5p6YJvLEpzf1VVuvE6-MXO9HXdJyPQy9xP0aZrEP5_cMIZdhmBetbO4Rim4Kp4yYvgy8W8oiP3cytYE3BHv6RqBO8_qe9OsEt1ta70r8RNCXK6quxXGHJ8j905GlVbkLxtLTue_9lQ9g1jA4LtOQPK5ap3e4pAANlCEtUQvYj6jd20mesWcsJhXbbaSDPFzIeyOGIfcoF_HdZE3js3ObwFaicNIdJafdT8QYqkHyFvIEl7InjJzx1c_NUirSAPvKZ6t8DBk&authuser=0&nonce=g9ojvsmp4our4&user=06555270420133642056&hash=6kn2vpvvfi257pon7cle8luh3ckltoj9
  ROM_NAME: Flyme
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
